### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Ben7230** [raphipod/iriun-fedora#1]
This is the output when I try to install. 

Last metadata expiration check: 1:13:18 ago on vie 07 abr 2023 09:26:56 CST.
Dependencies resolved.
===============================================================================================================================================================
 Package                                 Architecture                       Version                             Repository                                Size
===============================================================================================================================================================
Installing:
 iriunwebcam                             x86_64                             2.8-2                               @commandline                             1.1 M

Transaction Summary
===============================================================================================================================================================
Install  1 Package

Total size: 1.1 M
Installed size: 3.6 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /etc from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /usr from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /usr/local from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /usr/local/bin from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /usr/share from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /usr/share/applications from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /usr/share/pixmaps from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
  file /etc/modprobe.d from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package kmod-30-2.fc37.x86_64
  file /etc/modules-load.d from install of iriunwebcam-2.8-2.x86_64 conflicts with file from package systemd-udev-251.14-2.fc37.x86_64

Please, any suggestions.

**Comment by raphipod** [comment]
Hey, thanks for your issue!

You have to install it directly via **rpm**.
I'll also make sure to put it into the README.

`sudo rpm -Uvh (PACKAGE_NAME) --force`

Note that this is just a workaround (hence the --force), but it works fine for the time being.

**Comment by Ben7230** [comment]
Ok so that worked to install it, and then I had to install v4l2loopback with "sudo dnf install v4l2loopback" 

But I still have a problem,

![: Screenshot_2023-04-13_16:51](https://user-images.githubusercontent.com/97363017/231900276-157aea1d-c770-46c0-bf59-34ce454e50a9.png)

 it can't seem to find my phone, and it is on the same network.

**Comment by raphipod** [comment]
You need to keep the app open and the phone on, and both devices have to be in the same network.
Have you changed anything regarding firewall/ports?

I don't know which port Iriun exactly uses, but it **could be** that your host PC is blocking that specific one.

Else, try rebooting your machine. 

If that all doesn't help, I am out for solutions and any errors are not on my end. 

It works flawlessly on my Fedora 37/Nobara PC on KDE.

**Comment by Ben7230** [comment]
Ok, my bad, yes there was a Firewall blocking it, its working good now.

Thanks for your work.

**Comment by raphipod** [comment]
Awesome. Glad you got it working.
